import Head from 'next/head';
import Nav from '@/components/Nav/Nav';
import Header from '@/components/Header/Header';
import axios from 'axios';
import Menu from '@/components/Menu/Menu';
import Specials from '@/components/Specials/Specials';

export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;

function Home({ imgUrls, imgGallery, imgSpecials }: any) {
	const style = {
		sections: `md:ml-[20vw]`,
	};
	//console.log(imgUrls[0].image.asset.url);
	return (
		<>
			<Head>
				<title>The Clouds Restaurant</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<section id="nav">
				<Nav />
			</section>

			<section
				id="header"
				className={style.sections}>
				<Header imgUrls={imgGallery} />
			</section>

			<section
				id="specials"
				className={style.sections}>
				<Specials imgUrls={imgSpecials} />
			</section>

			<section
				id="menu"
				className={style.sections}>
				<Menu imgUrls={imgUrls} />
			</section>
		</>
	);
}
export const getServerSideProps = async () => {
	const resGetAllImgUrls = await axios.get(`${BASE_URL}/api/fetch-all-images`);
	const resGetAllGallery = await axios.get(`${BASE_URL}/api/fetch-all-gallery`);
	const resGetAllSpecials = await axios.get(
		`${BASE_URL}/api/fetch-all-specials`,
	);
	// const resGetSpecificImgUrl = await axios.get(
	// 	`${BASE_URL}/api/fetch-specific-image/slideimg3`,
	// );
	return {
		props: {
			imgUrls: resGetAllImgUrls.data,
			imgGallery: resGetAllGallery.data,
			imgSpecials: resGetAllSpecials.data,
			// specificImgUrl: resGetSpecificImgUrl.data,
		},
	};
};
export default Home;
