import Head from 'next/head';
import Header from '@/components/Header/Header';
import Presentation from '@/components/Presentation';
import axios from 'axios';

export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;

function Home({ imgUrls }: any) {
	const style = {
		content: `mt-[12vh] md:mt-0 md:ml-[20vw]`,
	};
	return (
		<>
			<Head>
				<title>The Clouds Restaurant</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<Header />

			<main className={style.content}>
				<Presentation imgUrls={imgUrls} />
			</main>
		</>
	);
}
export const getServerSideProps = async () => {
	const res = await axios.get(`${BASE_URL}/api/fetch-images`);
	return {
		props: {
			imgUrls: res.data,
		},
	};
};
export default Home;
